// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5z62f7eQUH4tLSVcN6RkdYYRH7WaoLOE',
    appId: '1:544442348448:web:4bac6519addfcd4cf86ac5',
    messagingSenderId: '544442348448',
    projectId: 'mynewanimalproject1',
    authDomain: 'mynewanimalproject1.firebaseapp.com',
    storageBucket: 'mynewanimalproject1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAByyBoB9lLiGvXVaHBVaF-x2b2a9mcvA',
    appId: '1:544442348448:android:8fad0c848af0321ff86ac5',
    messagingSenderId: '544442348448',
    projectId: 'mynewanimalproject1',
    storageBucket: 'mynewanimalproject1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWA-6vRat1i4BSa5fj4EXYgTYxYSU8CY4',
    appId: '1:544442348448:ios:83cba66b57004890f86ac5',
    messagingSenderId: '544442348448',
    projectId: 'mynewanimalproject1',
    storageBucket: 'mynewanimalproject1.appspot.com',
    iosClientId: '544442348448-gon7sf1ac1285oo596fm79cc2m8n1vmv.apps.googleusercontent.com',
    iosBundleId: 'com.example.newproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWA-6vRat1i4BSa5fj4EXYgTYxYSU8CY4',
    appId: '1:544442348448:ios:83cba66b57004890f86ac5',
    messagingSenderId: '544442348448',
    projectId: 'mynewanimalproject1',
    storageBucket: 'mynewanimalproject1.appspot.com',
    iosClientId: '544442348448-gon7sf1ac1285oo596fm79cc2m8n1vmv.apps.googleusercontent.com',
    iosBundleId: 'com.example.newproject',
  );
}
